### ISSUE TITLE
Reporte de Práctica #1 - Práctica de Hilos

### ISSUE THREAD

**Issue by IsaHuerta23** [SistemasTecTlaxiaco/practica-de-hilos-IsaHuerta23#2]
Reporte de Práctica #1 - Práctica de Hilos

[Sprint 3 - Reporte de Práctica #1.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-IsaHuerta23/files/6497530/Sprint.3.-.Reporte.de.Practica.1.pdf)

**Comment by IsraelNicolas61** [comment]
Calificación: 20

Calificó: Imanol García, Israel Nicolás y Uzias López

**Comment by josealfredo79** [comment]
Bien hecho y revisado

**Comment by josealfredo79** [comment]
Bien hecho y revisado
